name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    strategy:
      fail-fast: false
      matrix:
        profile: [ Debug, Release, Fast ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install dependencies
        run: ./helper.py -d
      - name: Build
        run: ./helper.py -b ${{ matrix.profile }}
      - name: Test
        run: ./helper.py -t ${{ matrix.profile }}